 jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - 12
      install:
        - npm ci
      script:
        - npm run build
        - npm test
    - stage: release
      name: "Create release notes with semantic-release"
      language: node_js
      node_js:
        - 12
      install:
        - npm i --save-dev --save-exact @semantic-release/git @semantic-release/changelog
      script:
        - npx semantic-release
    - stage: deploy
      name: "Deploy to Now"
      git:
        clone: false
      language: node_js
      node_js:
        - 12
      install:
        - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git checkout master
        - npm i -g now
      script:
        - now --token=$NOW_TOKEN --prod
stages:
  - test
  - release
    if: branch = master AND type != pull_request
  - deploy
    if: branch = master AND type != pull_request
