 jobs:
  include:
    - stage: release
      language: node_js
      node_js:
        - 12
      install:
        - npm i -D @semantic-release/commit-analyzer @semantic-release/release-notes-generator
          @semantic-release/github
      script:
        - npx semantic-release
	  - stage: deploy
      language: node_js
      node_js:
        - 12
      install:
        - npm i -g now
      script:
        - now --token=$NOW_TOKEN --target=production
stages:
  - release
    if: branch = master AND type != pull_request
  - name: deploy
    if: branch = master AND type != pull_request
